/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// AdmissionConstraintsApplyConfiguration represents a declarative configuration of the AdmissionConstraints type for use
// with apply.
type AdmissionConstraintsApplyConfiguration struct {
	// allowedResourceFlavors defines the list of ResourceFlavors a Workload can admit to.
	// If not specified, a Workload can admit to any ResourceFlavor.
	AllowedResourceFlavors []kueuev1beta2.ResourceFlavorReference `json:"allowedResourceFlavors,omitempty"`
}

// AdmissionConstraintsApplyConfiguration constructs a declarative configuration of the AdmissionConstraints type for use with
// apply.
func AdmissionConstraints() *AdmissionConstraintsApplyConfiguration {
	return &AdmissionConstraintsApplyConfiguration{}
}

// WithAllowedResourceFlavors adds the given value to the AllowedResourceFlavors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedResourceFlavors field.
func (b *AdmissionConstraintsApplyConfiguration) WithAllowedResourceFlavors(values ...kueuev1beta2.ResourceFlavorReference) *AdmissionConstraintsApplyConfiguration {
	for i := range values {
		b.AllowedResourceFlavors = append(b.AllowedResourceFlavors, values[i])
	}
	return b
}
