/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

import (
	kueuev1beta2 "sigs.k8s.io/kueue/apis/kueue/v1beta2"
)

// ConcurrentAdmissionMigrationConstraintsApplyConfiguration represents a declarative configuration of the ConcurrentAdmissionMigrationConstraints type for use
// with apply.
type ConcurrentAdmissionMigrationConstraintsApplyConfiguration struct {
	// mode defines the mode of Workload's migration.
	Mode *kueuev1beta2.ConcurrentAdmissionMigrationMode `json:"mode,omitempty"`
	// minTargetFlavor defines the minimal flavor a Workload can migrate to.
	// The order is based on the order of flavors in ClusterQueue.
	// It can only be used if the Mode is `UpgradeOnly` and `ExplicitVariants` is not specified.
	// If the Mode is `UpgradeOnly` and MinTargetFlavor is not specified, then there's
	// no constraints on what flavors a Workload can migrate to.
	MinTargetFlavor *kueuev1beta2.ResourceFlavorReference `json:"minTargetFlavor,omitempty"`
}

// ConcurrentAdmissionMigrationConstraintsApplyConfiguration constructs a declarative configuration of the ConcurrentAdmissionMigrationConstraints type for use with
// apply.
func ConcurrentAdmissionMigrationConstraints() *ConcurrentAdmissionMigrationConstraintsApplyConfiguration {
	return &ConcurrentAdmissionMigrationConstraintsApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *ConcurrentAdmissionMigrationConstraintsApplyConfiguration) WithMode(value kueuev1beta2.ConcurrentAdmissionMigrationMode) *ConcurrentAdmissionMigrationConstraintsApplyConfiguration {
	b.Mode = &value
	return b
}

// WithMinTargetFlavor sets the MinTargetFlavor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinTargetFlavor field is set to the value of the last call.
func (b *ConcurrentAdmissionMigrationConstraintsApplyConfiguration) WithMinTargetFlavor(value kueuev1beta2.ResourceFlavorReference) *ConcurrentAdmissionMigrationConstraintsApplyConfiguration {
	b.MinTargetFlavor = &value
	return b
}
