/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// ConcurrentAdmissionApplyConfiguration represents a declarative configuration of the ConcurrentAdmission type for use
// with apply.
type ConcurrentAdmissionApplyConfiguration struct {
	// migrationConstraints defines the constraints of Variants migration
	MigrationConstraints *ConcurrentAdmissionMigrationConstraintsApplyConfiguration `json:"migrationConstraints,omitempty"`
}

// ConcurrentAdmissionApplyConfiguration constructs a declarative configuration of the ConcurrentAdmission type for use with
// apply.
func ConcurrentAdmission() *ConcurrentAdmissionApplyConfiguration {
	return &ConcurrentAdmissionApplyConfiguration{}
}

// WithMigrationConstraints sets the MigrationConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MigrationConstraints field is set to the value of the last call.
func (b *ConcurrentAdmissionApplyConfiguration) WithMigrationConstraints(value *ConcurrentAdmissionMigrationConstraintsApplyConfiguration) *ConcurrentAdmissionApplyConfiguration {
	b.MigrationConstraints = value
	return b
}
